import { configureStore, createSlice } from '@reduxjs/toolkit';

// Create a slice for settings
const settingsSlice = createSlice({
  name: 'settings',
  initialState: {
    selectedPostTypeId: 2,
    selectedPublicationId: 1,
  },
  reducers: {
    setSelectedPostTypeId: (state, action) => {
      state.selectedPostTypeId = action.payload;
    },
    setSelectedPublicationId: (state, action) => {
      state.selectedPublicationId = action.payload;
    },
  },
});

// Extract action creators from the slice
export const { setSelectedPostTypeId, setSelectedPublicationId } = settingsSlice.actions;

// Use the reducer generated by createSlice directly as rootReducer
const rootReducer = settingsSlice.reducer;

// Create the Redux store
const store = configureStore({
  reducer: rootReducer,
  // Other store configuration options if needed
});

export default store;
